### ISSUE TITLE
is it possible to add support for proteus?

### ISSUE THREAD

**Issue by plandem** [micro/protoc-gen-micro#13]
Here is short article about reasons:

https://blog.sourced.tech/post/proteus/

It would really cool to be able to generate micro definition via proteus, because in our case we also use go as source to trust.

**Comment by asim** [comment]
How do you imagine it working? What are the steps to do this? What would be the benefit?

**Comment by plandem** [comment]
1) Benefits are same as at article: you code your models in Go and that's the only source to trust.
2) Right now we can generate proto and GRPC services implementation from Go models via proteus, but we can't auto generate micro implementation.
3) have a way to generate only micro implementation at least. In that case we will have 2 phase (1st step to generate proto and GRPC via proteus and next step to generate micro implementation only...somehow)

**Comment by asim** [comment]
Is there a high demand for proteus in the industry? What company are you working with? What do we need to do here to support proteus?

**Comment by plandem** [comment]
E.g.: If it will be possible to use addition cli arg to generate micro definition only - that would be enough. Something like this.

```
protoc --micro_only --proto_path=$GOPATH/src:. --micro_out=. --go_out=. greeter.proto
```
