### ISSUE TITLE
Cann't generate grpc code in the *.pb.go file

### ISSUE THREAD

**Issue by zuiaiqun** [micro/protoc-gen-micro#18]
I have followed the `greeter` example to generate the proto files. But I cann't see any grpc codes in the file.
Here is whate I've done:
* `protoc --proto_path=$CURRENTDIR/proto --micro_out=./src/share/pb --go_out=./src/share/pb $CURRENTDIR/proto/*.proto`

The output also has two files, one is the `greeter.micro.go`, the other is `greeter.pb.go`. However, the `greeter.pb.go` file doesn't have any codes relative to grpc.
My protoc version is `libprotoc 3.6.1`.
I use `go install github.com/micro/protoc-gen-micro` to get the `protoc-gen-micro` binary, and use `go install `go install github.com/golang/protobuf/protoc-gen-go` to get the `protoc-gen-go` binary.

Below is a snippet of the code:
`// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
    Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
    XXX_NoUnkeyedLiteral struct{} `json:"-"`
    XXX_unrecognized     []byte   `json:"-"`
    XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
    return fileDescriptor_greeter_7ab6ac6608e3c1bc, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
    return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
    return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
    xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
    return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
    xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
    if m != nil {
        return m.Name
    }
    return ""
}

type HelloResponse struct {
    Greeting             string   `protobuf:"bytes,2,opt,name=greeting,proto3" json:"greeting,omitempty"`
    XXX_NoUnkeyedLiteral struct{} `json:"-"`
    XXX_unrecognized     []byte   `json:"-"`
    XXX_sizecache        int32    `json:"-"`
}
`

**Comment by zuiaiqun** [comment]
When I run the client, the server can receive the requests, but the client cann't receive any data.

**Comment by asim** [comment]
Is the bin directory where protoc-gen-go in your `PATH`. If not, protoc will not find it and will not generate the code. Also note micro code is generated with a `*.micro.go` file extension.

**Comment by asim** [comment]
Also note we do not support the grpc generated code or framework. If you want to use gRPC the framework you need to see their instructions for how to build it.

**Comment by asim** [comment]
Has it generated a file with extension `micro.go`?

**Comment by zuiaiqun** [comment]
Yes. The output also has two files, one is the greeter.micro.go, the other is greeter.pb.go.

**Comment by asim** [comment]
The code you're expecting lives in greeter.micro.go. If you're expecting grpc generated code, you need to continue to specify the grpc plugin `--go_out=plugins=grpc`.

**Comment by zuiaiqun** [comment]
I've tried the way you mentioned above like this `protoc --proto_path=$CURRENTDIR/proto --micro_out=./src/share/pb --go_out=plugins=grpc:./src/share/pb $CURRENTDIR/proto/*.proto`.
The output seems that it can generate grpc code, but the grpc namespace is not the same as the example `/go.micro.srv.greeter.Say/Hello`.
Is there any problem? If yes, how can I solve it?
`
func (c *thirdTokenServiceClient) GetToken(ctx context.Context, in *GetTokenReq, opts ...grpc.CallOption) (*GetTokenRep, error) {
    out := new(GetTokenRep)
    err := c.cc.Invoke(ctx, "/pb.ThirdTokenService/GetToken", in, out, opts...)
    if err != nil {
        return nil, err 
    }   
    return out, nil 
}
`

**Comment by asim** [comment]
I cannot help you with grpc code. We support the protocol not the framework. I believe you need to set package name to change the namespace.

**Comment by zuiaiqun** [comment]
Thanks a lot!
