### ISSUE TITLE
own package importing

### ISSUE THREAD

**Issue by dmytriiandriichuk** [micro/protoc-gen-micro#26]
There is a small problem with the inclusion of proto in the same directory.

let's imagine that i have the following structure.
```
.
└── app
    └── service
        ├── a.proto
        └── b.proto
```

a.proto
```proto
syntax = "proto3";

package service;

message FooType {
    string Foo = 1;
}
```

b.proto
```proto
syntax = "proto3";

package service;

import "a.proto";

message BarType {
    FooType Foo = 1;
}
```

And if we try to generate micro.go for b.proto we'w receive own package import in b.micro.go. Actually, just like in this issue #21.
```go
import _ "app/service"
``` 

In my humble opinion, the whole problem is that own imports are not skipped:
https://github.com/micro/protoc-gen-micro/blob/5b1dcd09938fc1f18e8c9e23dc01947c696a7a2d/generator/generator.go#L1334

Can I suggest a fix?

**Comment by asim** [comment]
Please provide a fix if you have one. I don't have time to debug this. Proto has a lot of edge cases. If you have something that honours other workflows and your own then please PR.

**Comment by dmytriiandriichuk** [comment]
RP #27. @asim could you take a look?

**Comment by dmytriiandriichuk** [comment]
Perhaps it is already a little bit late for such statements, but there was a mistake in the fix that I proposed. Thanks for checking PR.

**Comment by asim** [comment]
No problem. Closing the issue
