### ISSUE TITLE
parsing go.mod: unexpected

### ISSUE THREAD

**Issue by zc2638** [micro/protoc-gen-micro#38]
when run ```go get github.com/micro/protoc-gen-micro```
it show:
```
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
```
I think you should modify go.mod

**Comment by asim** [comment]
Did you try go get -u?

**Comment by zc2638** [comment]
@asim Of course I tried.
If don't use ```go module```,it works fine.
But,the mod file write ```github.com/golang/lint``` conflict with origin package mod file.

**Comment by asim** [comment]
These guys are destroying everything.

**Comment by zc2638** [comment]
@asim Why not modify it to make go mod available?

**Comment by asim** [comment]
What do you  mean make it available?

**Comment by asim** [comment]
Try master or 0.7.1 now?

**Comment by zc2638** [comment]
@asim I mean you should change mod file 
```
replace github.com/golang/lint => golang.org/x/lint v0.0.0-20190301231843-5614ed5bae6f
```
to 
```
require golang.org/x/lint v0.0.0-20190301231843-5614ed5bae6f
```
And 0.7.1 is also failed
```
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
```

**Comment by asim** [comment]
I deleted my repo, I did go get, I did go get -u in the repo, it all builds clean. Are you sure you're updating?

**Comment by zc2638** [comment]
yeah,I'm sure.
I create a new test to run just now.
```
go $cd test/
test $go mod init test
go: creating new go.mod: module test
test $go get -u github.com/micro/protoc-gen-micro
go: finding golang.org/x/net latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/crypto latest
go: finding honnef.co/go/tools latest
go: finding github.com/armon/go-metrics latest
go: finding golang.org/x/lint latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/oauth2 latest
go: finding github.com/armon/circbuf latest
go: finding golang.org/x/tools latest
go: finding gopkg.in/check.v1 latest
go: finding github.com/google/btree latest
go: finding github.com/google/pprof latest
go: finding golang.org/x/build latest
go: finding github.com/jstemmer/go-junit-report latest
go: finding github.com/tarm/serial latest
go: finding google.golang.org/genproto latest
go: finding github.com/coreos/go-systemd latest
go: finding github.com/bradfitz/go-smtpd latest
go: finding github.com/golang/lint latest
go: finding golang.org/x/exp latest
go: finding golang.org/x/time latest
go: finding github.com/gregjones/httpcache latest
go: finding github.com/flynn/go-shlex latest
go: finding golang.org/x/perf latest
go: finding github.com/jellevandenhooff/dkim latest
go: finding github.com/golang/glog latest
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
go: finding github.com/prometheus/procfs latest
go: finding github.com/beorn7/perks latest
go: finding grpc.go4.org latest
go: finding go4.org latest
go get: error loading module requirements
```

**Comment by asim** [comment]
OK this is because you are building protoc-gen-micro as a submodule of your module which doesn't make sense because protoc-gen-micro is a standalone tool. So the replace statement in our go.mod file is not reflected in yours. This sub dependency becomes an issue. We just do go get -u so I'm not sure if its appropriate to modify the require statement or not.

**Comment by zc2638** [comment]
yes,this is what I want tell you.

**Comment by asim** [comment]
Yes but you shouldn't download a binary into a new project that uses go mod right? Or am I wrong? Is there a use case here?

**Comment by zc2638** [comment]
You are right!
But at first I just want to download with module unified management.
Maybe I can distinguish ```go tool``` from ```go project``` management.

**Comment by zc2638** [comment]
@asim When settings ```GO111MODULE=on```, it will go wrong.
To fix this problem, I submitted pr and think it will be help.
