### ISSUE TITLE
go-micro import version problem on generated code

### ISSUE THREAD

**Issue by luqmansen** [micro/protoc-gen-micro#64]
Protoc version 
```
 protoc --version
libprotoc 3.11.2
```
Go version 
```
go version  
go version go1.13.5 linux/amd64
```
Micro version
```
micro -v
micro version 1.18.0
```
Step to reproduce error
```
micro new helloworld --gopath=false
cd helloworld
go mod init helloworld
go run main.go
```
Run micro web client and call the endpoint from the web interface will throw an error to the output 
```
{
  "id": "go.micro.client.transport",
  "code": 500,
  "detail": "malformed HTTP response \"\\x00\\x00\\x06\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x05\\x00\\x00@\\x00\"",
  "status": "Internal Server Error"
}
```
## Problem
Every go file that generated from command "micro new <service name> " will be importing from "github.com/micro/go-micro" while protoc-gen-micro will generate file go file that importing from "github.com/micro/go-micro/v2". 
 
Manually change every file to import to ../go-micro/v2 not fixing the problem, while changing the protobuff and micro generated code will fix the problem, but that means every time protobuf boilterplate code regenerated, I need to manually change that import.

**Comment by vtolstov** [comment]
You need to use micro/micro/v2 binary

**Comment by luqmansen** [comment]
> You need to use micro/micro/v2 binary

Thanks, I didn't realize I used different versions for micro to call the service and for the import. This resolved the issue. Thanks again!
