### ISSUE TITLE
go get  protoc-gen-micro error

### ISSUE THREAD

**Issue by fengpf** [micro/protoc-gen-micro#65]
go get github.com/micro/protoc-gen-micro
go: github.com/micro/go-micro/v2@v2.0.0 requires
	github.com/mholt/certmagic@v0.9.1: gzip: invalid header

**Comment by nicocesar** [comment]
Is this still a thing? I had no issue, make sure to have have env variable:  `GO111MODULE=on`

**Comment by eJon** [comment]
go get github.com/micro/protoc-gen-micro/v2
